name: Release
on:
  push:
    tags:
      - "*.*.*"
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
      - id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Install dependencies
        run: |
          go install github.com/mitchellh/gox@latest
          go install github.com/tcnksm/ghr@latest
      - name: Build
        run: make all
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
      - name: Create release
        run: ./new_release.sh
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
